import Link from "next/link";
const InterpretationAndDefinitions = () => {
  return (
    <>
      {/* Interpretation and Definitions  */}
      <div id="interpretation-and-definitions" className="mb-10 md:mb-14">
        <h2 className="text-[18px] md:text-[20px] text-[#AE7E56] leading-[140%] font-[500] mb-4 md:mb-6">
          Interpretation and Definitions
        </h2>
        <div className="text-[32px] md:text-[40px] leading-[115%] tracking-[-0.01em] md:tracking-[-0.02em] mb-4 md:mb-6 headers-font">
          Interpretation
        </div>
        <p className="text-[16px]  md:text-[18px] leading-[160%] font-[400] text-[#000000D9] mb-6">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <div className="text-[32px] md:text-[40px] leading-[115%] tracking-[-0.01em] md:tracking-[-0.02em] mb-4 md:mb-6 headers-font">
          Definitions
        </div>
        <p className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          For the purposes of this Privacy Policy:
        </p>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Account </span>
          means a unique account created for You to access our Service or parts
          of our Service.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Company </span>
          (referred to as either “the Company”, “We”, “Us” or “Our” in this
          Agreement) refers to MyRocky Health Inc., 30 Wellington Street West,
          Toronto, Ontario.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Cookies </span>
          are small files that are placed on Your computer, mobile device or any
          other device by a website, containing the details of Your browsing
          history on that website among its many uses.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Country </span>
          refers to: Florida, US
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Device </span>
          means any device that can access the Service such as a computer, a
          cellphone or a digital tablet.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">
            Personal Data{" "}
          </span>
          is any information that relates to an identified or identifiable
          individual.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Service </span>
          refers to the Website.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">
            Service Provider{" "}
          </span>
          means any natural or legal person who processes the data on behalf of
          the Company. It refers to third-party companies or individuals
          employed by the Company to facilitate the Service, to provide the
          Service on behalf of the Company, to perform services related to the
          Service or to assist the Company in analyzing how the Service is used.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">
            Third-party Social Media Service{" "}
          </span>
          refers to any website or any social network website through which a
          User can log in or create an account to use the Service.
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Usage Data </span>
          refers to data collected automatically, either generated by the use of
          the Service or from the Service infrastructure itself (for example,
          the duration of a page visit).
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400]">
          <span className="font-[600] opacity-100 mt-4 mb-4">Website </span>
          refers to MyRocky, accessible from{" "}
          <Link
            href="/"
            className="duration-300 hover:text-gray-800 underline "
          >
            www.myrocky.com
          </Link>
        </div>

        <div className="text-[16px] mb-4  md:text-[18px] leading-[160%] font-[400] ">
          <span className="font-[600] opacity-100 mt-4 mb-4">You </span>
          means the individual accessing or using the Service, or the company,
          or other legal entity on behalf of which such individual is accessing
          or using the Service, as applicable.
        </div>
      </div>
    </>
  );
};

export default InterpretationAndDefinitions;
