export default function DisclaimerOfWarranties() {
  return (
    <div id="disclaimer-of-warranties" className="mb-10 md:mb-14">
      <div className="text-[22px] md:text-[30px] leading-[115%] tracking-[-0.01em] md:tracking-[-0.02em] mb-4 md:mb-6 headers-font">
        Disclaimer of warranties
      </div>
      <p className="text-[16px] md:text-[18px] leading-[160%] font-[400] text-[#000000D9] mb-6">
        YOU EXPRESSLY AGREE THAT USE OF THE SITES IS AT YOUR SOLE RISK. YOU
        ACKNOWLEDGE AND AGREE THAT THE SITES AND ANY SERVICES ARE PROVIDED
        THROUGH THE SITES ON AN “AS IS” AND “AS AVAILABLE” BASIS. MYROCKY AND ITS
        AFFILIATES, INCLUDING WITHOUT LIMITATION ALL AFFILIATED PROFESSIONAL
        ENTITIES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, MANAGERS, PARTNERS,
        MEMBERS, EMPLOYEES, AND AGENTS (COLLECTIVELY “ <b> RELATED PERSONS </b>
        ”) MAKE NO REPRESENTATIONS OR WARRANTIES AND EXPRESSLY DISCLAIM ANY AND
        ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, WITH RESPECT TO
        THE SITES AND SERVICES INCLUDING, BUT NOT LIMITED TO, ANY
        REPRESENTATIONS OR WARRANTIES WITH RESPECT TO MERCHANTABILITY, FITNESS
        FOR A PARTICULAR USE OR PURPOSE, NONINFRINGEMENT, TITLE, AVAILABILITY,
        SECURITY, OPERABILITY, CONDITION, QUIET ENJOYMENT, VALUE, ACCURACY OF
        DATA, FREEDOM FROM VIRUSES OR MALWARE, COMPLETENESS, TIMELINESS,
        FUNCTIONALITY, RELIABILITY, SEQUENCING OR SPEED OF DELIVERY OR SYSTEM
        INTEGRATION. WE MAKE NO WARRANTIES OR REPRESENTATIONS THAT YOUR USE OF
        THE SITES OR SERVICES WILL NOT INFRINGE THE RIGHTS OF THIRD PARTIES.
      </p>
      <p className="text-[16px] md:text-[18px] leading-[160%] font-[400] text-[#000000D9] mb-6">
        TO THE FULLEST EXTENT OF APPLICABLE LAW, NEITHER MYROCKY NOR ITS RELATED
        PERSONS WILL BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY YOUR RELIANCE ON
        INFORMATION OBTAINED THROUGH THE SITES. IT IS YOUR RESPONSIBILITY TO
        EVALUATE THE ACCURACY, COMPLETENESS, TIMELINESS, RELIABILITY OR
        USEFULNESS OF THE SITES. FURTHERMORE, MYROCKY DOES NOT GUARANTEE THAT THE
        SITES WILL BE UNINTERRUPTED, OR FREE FROM ERROR, DEFECT, LOSS, DELAY IN
        OPERATION, CORRUPTION, CYBER ATTACK, VIRUSES, INTERFERENCE, HACKING,
        MALWARE, OR OTHER SECURITY INTRUSION, AND MYROCKY DISCLAIMS ANY LIABILITY
        RELATING THERETO.
      </p>
      <p className="text-[16px] md:text-[18px] leading-[160%] font-[400] text-[#000000D9] mb-6">
        YOU UNDERSTAND AND AGREE THAT ANY CONTENT, MATERIAL AND/OR INFORMATION
        OBTAINED THROUGH THE USE OF THE SITES ARE USED AT YOUR SOLE RISK AND
        THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER OR
        MOBILE PHONE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH
        CONTENT, MATERIAL AND/OR INFORMATION.
      </p>
    </div>
  );
}
