export const prEdQuiz2Config = {
  defaultDestinationHref: "/ed-pre-consultation-quiz",
  /** Linked from the medical disqualification modal (“Contact support”). */
  disqualifySupportUrl: "https://myrocky.com/contact/",
  steps: [
    {
      id: "q1",
      type: "multiSelect",
      title: "What are you looking to improve?",
      subtitle: "Select all that apply.",
      options: [
        "Last longer",
        "Better erections",
        "More arousal",
        "Faster rebound time",
        "More confidence",
      ],
    },
    {
      id: "q2",
      type: "imageContinue",
      hideWizardHeader: true,
      imageSrc: "/ed-1/man4.jpg",
      imageAlt: "DirectMax customer",
      headlineLines: ["91% of men prefer", "DirectMax over other", "ED treatments*"],
      footnote: "*Based on a survey of Direct Meds active patients.",
      ctaLabel: "Continue",
    },
    {
      id: "q3",
      type: "trustedReviews",
      hideWizardHeader: true,
      title: "Trusted by over 175k+ men",
      ctaLabel: "Continue",
      reviews: [
        {
          title: "Best thing I've tried",
          body: "It shipped really fast. I love that it came unmarked. I have teenage boys, can't have them stealing this stuff from me lol. Works wonders. I've tried Rugiet, Viagra etc. and this is by far the better one.",
          author: "Mike.",
        },
        {
          title: "I got this for my wife",
          body: "Sex has always been good, but I thought we would have a little fun. I haven't told her I use it. She just thinks I always have a rager. Really boosted her confidence and I'm having a whole lot more fun. Climax is freaking epic.",
          author: "J.R.",
        },
        {
          title: "It's like I'm 18 again",
          body: "I was really struggling getting going. DirectMax is awesome. I feel like a teenager again and thats saying alot because im almost 60. I have a few girlfriends I mess around with and I can actually keep up. Sure helps me get my cardio in.",
          author: "Johnny P.",
        },
        {
          title: "Whoa buddy this is legit",
          body: "100% of the time, it works all the time. Seriously I ordered the medium dose and I actually just use a quarter of it for casual sex or a full one when I want to really get weird.",
          author: "Kyle",
        },
        {
          title: "The Missing Key",
          body: "I'm writing a review for my husband. I made him order the direct max after seeing an ad on his phone. He was so nervous to try it and I was scared it wouldnt work and make me feel self concious as usual. In about 15 minutes he gave me a crazy look and now we're always using it. WE BOTH LOVE IT!!!",
          author: "Samantha J.",
        },
      ],
    },
    {
      id: "q4",
      type: "eligibilityForm",
      hideWizardHeader: true,
      showTopProgress: true,
      title: "Let's make sure you're eligible for treatment",
      subtitle:
        "A few basics help us confirm you can be treated safely. On the next step, you'll sign in to myRocky or create an account—we'll collect your name, email, phone, and password there before we apply your discounts.",
      ctaLabel: "Continue",
    },
    {
      id: "q5",
      type: "patientInfoForm",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Patient info",
      headline:
        "This is looking great! Last thing we need before we apply your discounts",
      introLine:
        "Same form whether you're logging in or registering: we'll use it for sign-in or account setup, then continue your intake.",
      privacyLine: "Your information is protected by HIPAA.",
      consentText:
        "By continuing, you confirm that you've read and agree to our Terms and Conditions, Professional Disclosure, Privacy Policy, Telehealth Consent and Implied Consent.",
      ctaLabel: "Continue",
    },
    {
      id: "q6",
      type: "stateAvailability",
      hideWizardHeader: true,
      titlePrefix: "Good news.",
      titleTemplate: "DirectMax is available in {stateName}",
      bullets: [
        "Our clinicians are licensed and able to ship to your state",
        "Medication ships to {stateName} addresses within 48 hours",
      ],
      ctaLabel: "Continue",
    },
    {
      id: "q7",
      type: "healthInfoIntro",
      hideWizardHeader: true,
      imageSrc: "/ed-1/dr1.jpg",
      imageAlt: "Board-certified physician",
      imageCaption: "All medications prescribed by Certified Physicians.",
      headline: "Looking great! Let's get some info about your health.",
      body: "Our board-certified physicians use the information in the following questions to tailor your treatment.",
      privacyNotice: "Your answers are private and HIPAA protected.",
      ctaLabel: "Continue",
    },
    {
      id: "q8",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "In the past 6 months",
      title: "How confident are you in getting or keeping an erection?",
      fieldName: "medication_ed_confidence",
      ctaLabel: "Continue",
      options: [
        { label: "Not confident", value: "not_confident" },
        { label: "Low confidence", value: "low_confidence" },
        { label: "Somewhat confident", value: "somewhat_confident" },
        { label: "Mostly confident", value: "mostly_confident" },
        { label: "Very confident", value: "very_confident" },
      ],
    },
    {
      id: "q9",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "In the past 6 months",
      title: "How often are your erections firm enough for intercourse?",
      fieldName: "medication_ed_erection_frequency",
      ctaLabel: "Continue",
      options: [
        { label: "Rarely or never", value: "rarely_or_never" },
        { label: "A few times", value: "a_few_times" },
        { label: "Sometimes", value: "sometimes" },
        { label: "Most times", value: "most_times" },
        { label: "Almost always or always", value: "almost_always_or_always" },
      ],
    },
    {
      id: "q10",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "In the past 6 months",
      title: "How often are you able to keep an erection after beginning intercourse?",
      fieldName: "medication_ed_maintain_after_intercourse",
      ctaLabel: "Continue",
      options: [
        { label: "Rarely or never", value: "rarely_or_never" },
        { label: "A few times", value: "a_few_times" },
        { label: "Sometimes", value: "sometimes" },
        { label: "Most times", value: "most_times" },
      ],
    },
    {
      id: "q11",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "In the past 6 months",
      title: "How often are you satisfied when attempting intercourse?",
      fieldName: "medication_ed_satisfaction_intercourse",
      ctaLabel: "Continue",
      options: [
        { label: "Rarely or never", value: "rarely_or_never" },
        { label: "A few times", value: "a_few_times" },
        { label: "Sometimes", value: "sometimes" },
        { label: "Most times", value: "most_times" },
        { label: "Almost always or always", value: "almost_always_or_always" },
      ],
    },
    {
      id: "q12",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Performance factors",
      title: "Is your sexual performance affected by any of the following?",
      fieldName: "medication_ed_performance_factors",
      ctaLabel: "Continue",
      options: [
        {
          label: "A feeling of nervousness or anxiety before and/or during sex",
          value: "nervousness_anxiety",
        },
        {
          label: "Concern about your sexual performance",
          value: "concern_sexual_performance",
        },
        {
          label: "Concern about your body image",
          value: "concern_body_image",
        },
        {
          label:
            "Concern about sexual dysfunction conditions you may have",
          value: "concern_dysfunction_conditions",
        },
        {
          label: "Relationship problems",
          value: "relationship_problems",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q13",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Your History",
      title: "Have you ever taken ED medications?",
      fieldName: "medication_ed_prior_use",
      ctaLabel: "Continue",
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
    },
    {
      id: "q14",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Your Health",
      title: "How often do you have sex?",
      fieldName: "medication_ed_sex_frequency",
      ctaLabel: "Continue",
      options: [
        { label: "Once a week or less", value: "once_week_or_less" },
        { label: "2-3 times per week", value: "two_to_three_per_week" },
        { label: "4 or more times per week", value: "four_or_more_per_week" },
      ],
    },
    {
      id: "q15",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Your History",
      title:
        "Have you had a physical exam with a healthcare provider in the past 2 years?",
      fieldName: "medication_ed_recent_physical_exam",
      ctaLabel: "Continue",
      options: [
        { label: "Yes, it was normal", value: "yes_normal" },
        {
          label: "Yes, but there were issues",
          value: "yes_with_issues",
        },
        { label: "No", value: "no" },
      ],
    },
    {
      id: "q16",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title:
        "Do you have any medical conditions or a history of prior surgeries?",
      fieldName: "medication_ed_conditions_or_surgeries",
      followUpWhenValue: "yes",
      followUpLabel: "Please briefly describe your condition(s) or surgery history:",
      followUpFieldName: "medication_ed_conditions_or_surgeries_detail",
      ctaLabel: "Continue",
      options: [
        { label: "No", value: "no" },
        { label: "Yes", value: "yes" },
      ],
      safeContinueValues: ["no"],
    },
    {
      id: "q17",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title:
        "Are you currently taking any medications, vitamins or dietary supplements?",
      fieldName: "medication_ed_current_meds_supplements",
      followUpWhenValue: "yes",
      followUpLabel:
        "Please list what you take (medications, vitamins, or supplements):",
      followUpFieldName: "medication_ed_current_meds_supplements_detail",
      ctaLabel: "Continue",
      options: [
        {
          label: "No, I don't take anything",
          value: "no",
        },
        { label: "Yes", value: "yes" },
      ],
    },
    {
      id: "q18",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "Do you have any allergies?",
      fieldName: "medication_ed_allergies",
      followUpWhenValue: "yes",
      followUpLabel: "Please describe your allergies:",
      followUpFieldName: "medication_ed_allergies_detail",
      ctaLabel: "Continue",
      options: [
        { label: "No", value: "no" },
        { label: "Yes", value: "yes" },
      ],
    },
    {
      id: "q19",
      type: "multiSelect",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "Do you take any of the following nitrates for chest pain?",
      subtitle: "Select all that apply.",
      fieldName: "medication_ed_nitrates",
      /** Only this sole selection may continue; any nitrate blocks progress. */
      solePassValue: "none_of_these",
      options: [
        { label: "Nitroglycerin", value: "nitroglycerin" },
        { label: "Amyl nitrate", value: "amyl_nitrate" },
        { label: "Nitrostat", value: "nitrostat" },
        { label: "GoNitro", value: "gonitro" },
        { label: "Nitrolingual spray", value: "nitrolingual_spray" },
        { label: "Nitromist", value: "nitromist" },
        { label: "Isosorbide dinitrate", value: "isosorbide_dinitrate" },
        {
          label: "Isosorbide mononitrate",
          value: "isosorbide_mononitrate",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q20",
      type: "multiSelect",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "Do you use any of the following recreational drugs?",
      subtitle: "Select all that apply.",
      fieldName: "medication_ed_recreational_drugs",
      solePassValue: "none_of_these",
      options: [
        { label: "Cocaine", value: "cocaine" },
        {
          label: "Poppers/Rush (amyl/butyl nitrate)",
          value: "poppers_amyl_butyl_nitrate",
        },
        { label: "Methamphetamines", value: "methamphetamines" },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q21",
      type: "multiSelect",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Prescription Interactions",
      title:
        "Do you take any of the following prescription medications?",
      subtitle: "Select all that apply.",
      fieldName: "medication_ed_prescription_interactions",
      solePassValue: "none_of_these",
      options: [
        {
          label:
            "Alpha blockers (alfuzosin, terazosin, doxazosin, tamsulosin)",
          value: "alpha_blockers",
        },
        {
          label: "Cimetidine, erythromycin or digitoxin",
          value: "cimetidine_erythromycin_digitoxin",
        },
        {
          label: "Ketoconazole or itraconazole",
          value: "ketoconazole_itraconazole",
        },
        { label: "Adempas (riociguat)", value: "adempas_riociguat" },
        { label: "Trazodone", value: "trazodone" },
        {
          label: "Ritonavir or saquinavir",
          value: "ritonavir_saquinavir",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q22",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "Do you have kidney disease?",
      fieldName: "medication_ed_kidney_disease",
      followUpWhenValue: "yes",
      followUpLabel: "Please briefly describe your kidney condition:",
      followUpFieldName: "medication_ed_kidney_disease_detail",
      ctaLabel: "Continue",
      options: [
        { label: "No", value: "no" },
        { label: "Yes", value: "yes" },
      ],
      safeContinueValues: ["no"],
    },
    {
      id: "q23",
      type: "multiSelect",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Genital Abnormalities",
      title: "Have you had any physical genital abnormalities?",
      subtitle: "Select all that apply.",
      fieldName: "medication_ed_genital_abnormalities",
      solePassValue: "none_of_these",
      options: [
        {
          label:
            "Previous priapism (erection lasting longer than 4 hours requiring medical treatment)",
          value: "previous_priapism",
        },
        { label: "Peyronie's disease", value: "peyronies_disease" },
        { label: "Painful bend in penis", value: "painful_bend_penis" },
        {
          label: "Genital surgery or pelvic trauma",
          value: "genital_surgery_pelvic_trauma",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q24",
      type: "multiSelect",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "Do you have any of the following conditions?",
      subtitle: "Select all that apply.",
      fieldName: "medication_ed_additional_conditions",
      solePassValue: "none_of_these",
      options: [
        {
          label:
            "Retinitis pigmentosa or anterior ischemic optic neuropathy",
          value: "retinitis_pigmentosa_or_aion",
        },
        {
          label: "Severe aortic stenosis or HOCM",
          value: "severe_aortic_stenosis_hocm",
        },
        {
          label: "Pulmonary hypertension",
          value: "pulmonary_hypertension",
        },
        {
          label: "Sickle cell, myeloma, or leukemia",
          value: "sickle_cell_myeloma_leukemia",
        },
        {
          label: "MS, spinal injuries, or paralysis",
          value: "ms_spinal_injuries_paralysis",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q25",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Medical Info",
      title: "What does your blood pressure usually run?",
      fieldName: "medication_ed_blood_pressure_range",
      ctaLabel: "Continue",
      /** Only “Very low” opens the disqualification modal on Continue. */
      disqualifyingValues: ["very_low_below_100_65"],
      options: [
        { label: "Normal (approx 120/80)", value: "normal_approx_120_80" },
        { label: "High (above 130/90)", value: "high_above_130_90" },
        { label: "Low (below 110/70)", value: "low_below_110_70" },
        {
          label: "Very low (below 100/65)",
          value: "very_low_below_100_65",
        },
        { label: "Not sure", value: "not_sure" },
      ],
    },
    {
      id: "q26",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Your Health",
      title:
        "Do you have any other health concerns you'd like to address?",
      fieldName: "medication_ed_other_health_concerns",
      ctaLabel: "Continue",
      options: [
        { label: "Weight loss", value: "weight_loss" },
        { label: "Hair loss", value: "hair_loss" },
        {
          label: "Low energy or fatigue",
          value: "low_energy_fatigue",
        },
        { label: "Sleep issues", value: "sleep_issues" },
        { label: "Stress or anxiety", value: "stress_anxiety" },
        {
          label: "Focus or concentration",
          value: "focus_concentration",
        },
        {
          label: "Sexual health concerns (non-erection)",
          value: "sexual_health_non_erection",
        },
        { label: "General wellness", value: "general_wellness" },
        {
          label: "Other (please specify)",
          value: "other_specify",
        },
        {
          label: "None of these",
          value: "none_of_these",
        },
      ],
    },
    {
      id: "q27",
      type: "singleSelectQuiz",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Additional Info",
      title:
        "Is there anything else you want your doctor to know about your condition or health?",
      fieldName: "medication_ed_doctor_additional_info",
      followUpWhenValue: "yes",
      followUpLabel: "Please share any additional details for your doctor:",
      followUpFieldName: "medication_ed_doctor_additional_info_detail",
      ctaLabel: "Continue",
      options: [
        { label: "No", value: "no" },
        { label: "Yes", value: "yes" },
      ],
    },
    {
      id: "q28",
      type: "processingLoader",
      hideWizardHeader: true,
      headline: "Processing your information...",
      checklist: ["Medical History", "Health Info", "ED Frequency"],
      durationMs: 4000,
    },
    {
      id: "q29",
      type: "productPitch",
      hideWizardHeader: true,
      imageSrc: "/ed-1/direct-max-pack.jpg",
      imageAlt: "DirectMax ED medication packaging",
      headline:
        "Meet the highest rated ED treatment loved by over 175K+ men",
      brandName: "DirectMax",
      subHeadRest:
        " 3-in-1 fast-acting ED medication delivered discreetly in 1-2 days.",
      features: [
        {
          icon: "flame",
          before: "Apomorphine ",
          highlight: "to boost arousal",
        },
        {
          icon: "compass",
          before: "Sildenafil ",
          highlight: "to get harder faster",
        },
        {
          icon: "clock",
          before: "Tadalafil ",
          highlight: "to stay hard longer",
        },
        {
          icon: "bolt",
          before: "",
          highlight: "Effects in 15 minutes or less",
          trailing: "*",
        },
      ],
      disclaimer: "*Individual results may vary.",
      footerItems: [
        { icon: "truck", label: "Fast Free Shipping" },
        { icon: "bolt", label: "Longer Bigger Faster" },
        { icon: "check", label: "3x better than Viagra®" },
      ],
      ctaLabel: "Continue",
    },
    {
      id: "q30",
      type: "chartPitch",
      hideWizardHeader: true,
      imageSrc: "/ed-1/directmax-chart.jpg",
      imageAlt:
        "Chart comparing time to onset: DirectMax vs Tadalafil vs Sildenafil",
      titleLine: "Get Hard",
      subtitleBefore: "in just ",
      subtitleHighlight: "15",
      subtitleAfter: " minutes.",
      disclaimer:
        "*On average, after medication dissolves. Based on a customer survey of active DirectMax patients.",
      ctaLabel: "Continue",
    },
    {
      id: "q31",
      type: "benefitsPitch",
      hideWizardHeader: true,
      imageSrc: "/ed-1/man-benefits.jpg",
      imageAlt:
        "Man in a light shirt on a neutral background",
      headline: "Now you'll be fully ready when it matters most.",
      statValue: "89%",
      statLead: "of men prefer ",
      statPhraseA: "apomorphine + sildenafil",
      statMid: " to ",
      statPhraseB: "sildenafil alone",
      statTrailing: "*",
      disclaimer:
        "*On average, after medication dissolves. Based on a customer survey of active DirectMax patients.",
      ctaLabel: "Continue",
    },
    {
      id: "q32",
      type: "processingLoader",
      hideWizardHeader: true,
      headline: "Preparing your plan...",
      checklist: [
        "Checking Availability",
        "Applying Discounts",
        "Customizing Treatment",
      ],
      durationMs: 4000,
    },
    {
      id: "q32_recommendation",
      type: "recommendationChoice",
      hideWizardHeader: true,
      showTopProgress: true,
      eyebrow: "Here's what we recommended",
      headline: "Your treatment plan",
      recommendedProductName: "Cialis + Viagra",
      ctaLabel: "Continue",
    },
    {
      id: "q33",
      type: "planApproval",
      hideWizardHeader: true,
      timerMinutes: 15,
      productImageSrc:
        "https://assets.directmeds.com/direct-max/1/direct-max-tabs-3.png",
      doctorImageSrc: "https://assets.directmeds.com/direct-max/1/dr1.jpg",
      ctaLabel: "Continue",
    },
  ],
};
